language: ruby

rvm:
  - 2.1.0

env:
  - PUPPET_VERSION="~> 2.7.20"
  - PUPPET_VERSION="~> 3.1.0"
  - PUPPET_VERSION="~> 3.2.0"
  - PUPPET_VERSION="~> 3.4.0"
  - PUPPET_VERSION="~> 3.6.0"
  - PUPPET_VERSION="~> 3.7.0"
  - PUPPET_VERSION="~> 4.3.0"
  - PUPPET_VERSION="~> 4.3.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.9.0"
  - PUPPET_VERSION="~> 5.5.0"

script: "rake test"

sudo: false
